# Generated by Django 2.2.6 on 2020-06-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
