# Generated by Django 2.2.6 on 2020-06-10 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tutorials', '0004_tutorial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
