# Generated by Django 2.2.6 on 2020-06-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_tutorial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='user',
        ),
    ]
