# Generated by Django 2.1.15 on 2020-06-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_auto_20200610_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='modified_date',
        ),
    ]
