# Generated by Django 2.1.15 on 2020-06-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0015_remove_tutorial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
