# Generated by Django 2.1.15 on 2020-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_auto_20200611_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
