# Generated by Django 2.1.15 on 2020-06-11 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_auto_20200611_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='published',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='created_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
