# Generated by Django 2.1.15 on 2020-06-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0018_auto_20200611_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
