# Generated by Django 2.1.15 on 2020-06-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0019_auto_20200611_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='created_date',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
