# Generated by Django 2.2.6 on 2020-06-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='content',
            field=models.TextField(default='', max_length=500),
        ),
    ]
