# Generated by Django 2.2.6 on 2020-06-10 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_remove_tutorial_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='modified_date',
        ),
    ]
